/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancopoly.guatemala;


import BloquesCasillas.Casilla;
import Jugadores.Jugador;
import Jugadores.PosicionFicha;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class Tablero extends javax.swing.JFrame {
      private final Jugador jugador1 = new Jugador(1);
    private final Jugador jugador2 = new Jugador(2);
    private Jugador jugadorActual = jugador1;
    int inicio,SanLucas,Atitlan,Bote,Panachel,Godinez,Chilero,SanAndres,SanJorge,Chafa,SanAntonio,SantaCatetina;
    


        
    public Tablero() {
        initComponents();
         setLocationRelativeTo(null);
        setResizable(false);
        setTitle("BancoPoly(Solola)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbn = new javax.swing.JLabel();
        lbn2 = new javax.swing.JLabel();
        jbutton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imagendado1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        lbnx = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancopoly/guatemala/FichaOro.jpg"))); // NOI18N
        lbn.setText("Jugador 1");
        getContentPane().add(lbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 80, 90));

        lbn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancopoly/guatemala/FichaPlata.jpg"))); // NOI18N
        lbn2.setText("Jugador 2");
        lbn2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbn2PropertyChange(evt);
            }
        });
        getContentPane().add(lbn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 80, 80));

        jbutton1.setText("Inicio(Recibe Q400)");
        jbutton1.setName("jbutton1"); // NOI18N
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 120));

        jButton2.setText("Bote");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 120));

        jButton3.setText("Chilero");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 170, 120));

        jButton4.setText("Chafa");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 170, 120));

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setText("San Lucas(Q250)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 120));

        jButton6.setBackground(new java.awt.Color(0, 102, 255));
        jButton6.setText("Atitlan(Q300)");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 120));

        jButton7.setBackground(new java.awt.Color(255, 51, 0));
        jButton7.setText("Panajachel(Q350)");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 170, 100));

        jButton8.setBackground(new java.awt.Color(255, 51, 0));
        jButton8.setText("Godinez(200)");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 170, 100));

        jButton9.setBackground(new java.awt.Color(255, 204, 0));
        jButton9.setText("San Andres(Q275)");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 140, 120));

        jButton10.setBackground(new java.awt.Color(255, 204, 0));
        jButton10.setText("San Jorge(Q290)");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 140, 120));

        jButton11.setBackground(new java.awt.Color(51, 204, 0));
        jButton11.setText("San Antonio(325)");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 170, 100));

        jButton12.setBackground(new java.awt.Color(51, 204, 0));
        jButton12.setText("Santa Catarina(270)");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 170, 100));

        jButton13.setText("Salir");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 70, 30));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("Lanzar Dado");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancopoly/guatemala/FichaOro.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancopoly/guatemala/FichaPlata.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, 80));

        imagendado1.setIcon(new javax.swing.ImageIcon("C:\\Users\\usuario\\Documents\\NetBeansProjects\\BancoPoly(Solola)\\src\\bancopoly\\solola\\dados-05.gif")); // NOI18N
        getContentPane().add(imagendado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 100, 90));

        jButton1.setText("Monto");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        jButton15.setText("Monto");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        lbnx.setForeground(new java.awt.Color(255, 255, 255));
        lbnx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancopoly/guatemala/fondo.png"))); // NOI18N
        getContentPane().add(lbnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private int nuevaCasilla(int casillaActual, int movimiento) {
        int casillaNueva = casillaActual + movimiento;
        if (casillaNueva > 12) {
            casillaNueva = casillaNueva - 12;
        }
        return casillaNueva;
    }
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Random rnd = new Random();
        int dado1 = 1;
        dado1 = ((int)(rnd.nextDouble()*6));
        int inicio,SanLucas,Atitlan,Bote,Panachel,Godinez,Chilero,SanAndres,SanJorge,Chafa,SanAntonio,SantaCatetina;
        
        
        if(dado1==1){  
        imagendado1.setIcon(new ImageIcon(getClass().getResource("1.png")));      
        int nuevaCasilla = nuevaCasilla(jugadorActual.getCasillaActual(),dado1);
        jugadorActual.setCasillaActual(nuevaCasilla);
        PosicionFicha nuevaPosicion = Casilla.nuevaPosicion(nuevaCasilla, jugadorActual.getId());
        if (jugadorActual.getId() == 1) {
           
            lbn.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador2;
        } else {
            lbn2.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador1;
        }        
        }     
        else if(dado1==2){
            imagendado1.setIcon(new ImageIcon(getClass().getResource("2.png")));
             int nuevaCasilla = nuevaCasilla(jugadorActual.getCasillaActual(),dado1);
        jugadorActual.setCasillaActual(nuevaCasilla);
        PosicionFicha nuevaPosicion = Casilla.nuevaPosicion(nuevaCasilla, jugadorActual.getId());
        if (jugadorActual.getId() == 1) {
            lbn.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador2;
        } else {
            lbn2.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador1;
        }
        }
        else if(dado1==3){
            imagendado1.setIcon(new ImageIcon(getClass().getResource("3.png")));
            int nuevaCasilla = nuevaCasilla(jugadorActual.getCasillaActual(),dado1);
        jugadorActual.setCasillaActual(nuevaCasilla);
        PosicionFicha nuevaPosicion = Casilla.nuevaPosicion(nuevaCasilla, jugadorActual.getId());
        if (jugadorActual.getId() == 1) {
            lbn.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador2;
        } else {
            lbn2.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador1;
        }
        }
        else if(dado1==4){
            imagendado1.setIcon(new ImageIcon(getClass().getResource("4.png")));
            int nuevaCasilla = nuevaCasilla(jugadorActual.getCasillaActual(),dado1);
        jugadorActual.setCasillaActual(nuevaCasilla);
        PosicionFicha nuevaPosicion = Casilla.nuevaPosicion(nuevaCasilla, jugadorActual.getId());
        if (jugadorActual.getId() == 1) {
            lbn.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador2;
        } else {
            lbn2.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador1;
        }
        }
        else if(dado1==5){
            imagendado1.setIcon(new ImageIcon(getClass().getResource("5.png")));
            int nuevaCasilla = nuevaCasilla(jugadorActual.getCasillaActual(),dado1);
        jugadorActual.setCasillaActual(nuevaCasilla);
        PosicionFicha nuevaPosicion = Casilla.nuevaPosicion(nuevaCasilla, jugadorActual.getId());
        if (jugadorActual.getId() == 1) {
            lbn.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador2;
        } else {
            lbn2.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador1;
        }
        }
        else if(dado1==6){
            imagendado1.setIcon(new ImageIcon(getClass().getResource("6.png")));
            int nuevaCasilla = nuevaCasilla(jugadorActual.getCasillaActual(),dado1);
        jugadorActual.setCasillaActual(nuevaCasilla);
        PosicionFicha nuevaPosicion = Casilla.nuevaPosicion(nuevaCasilla, jugadorActual.getId());
        if (jugadorActual.getId() == 1) {
            lbn.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador2;
        } else {
            lbn2.setLocation(nuevaPosicion.getX(), nuevaPosicion.getY());
            jugadorActual = jugador1;
        }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void lbn2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbn2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lbn2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagendado1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbutton1;
    private javax.swing.JLabel lbn;
    private javax.swing.JLabel lbn2;
    private javax.swing.JLabel lbnx;
    // End of variables declaration//GEN-END:variables
}
